jobs:

- template: run-tox-env.yml
  parameters:
    envs:
    - linux: py37-simple-linux
    - linux32: py37-simple-linux32
    - macos: py37-simple-macos
    - windows: py37-simple-windows


- template: run-tox-env.yml
  parameters:
    mesaopengl: true
    envs:
    - macos: py37-opengl-macos
    - windows: py37-opengl-windows
