parameters:
  python_versions:
    - 3.7
    - 3.6

jobs:
- ${{ each target in parameters.targets }}:

  - ${{ if or(eq(target, 'wheels_macosx'), eq(target, 'wheels_linux'), eq(target, 'wheels_windows')) }}:

    - job: ${{ target }}
      dependsOn: ${{ parameters.dependsOn }}
      condition: succeeded()

      variables:
        CIBW_TEST_COMMAND: ${{ parameters.test_command }}
        CIBW_TEST_EXTRAS: ${{ parameters.test_extras }}

      pool:
        ${{ if eq(target, 'wheels_macosx') }}:
          vmImage: macOS 10.13
        ${{ if eq(target, 'wheels_linux') }}:
          vmImage: Ubuntu 16.04
        ${{ if eq(target, 'wheels_windows') }}:
          vmImage: vs2017-win2016

      steps:
        - ${{ if not(eq(target, 'wheels_windows')) }}:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ parameters.python_versions[0] }}
        - ${{ if eq(target, 'wheels_windows') }}:
          - ${{ each version in parameters.python_versions }}:
            - task: UsePythonVersion@0
              inputs:
                versionSpec: ${{ version }}
        - bash: python -m pip install --upgrade pip
          displayName: Upgrading pip
        - bash: python -m pip install cibuildwheel
          displayName: Installing cibuildwheel
        - bash: cibuildwheel --output-dir wheelhouse .
          displayName: Running cibuildwheel
        - publish: 'wheelhouse'
          artifact: ${{ target }}

  - ${{ if eq(target, 'sdist') }}:
    - job: ${{ target }}
      dependsOn: ${{ parameters.dependsOn }}
      condition: succeeded()
      pool: {vmImage: 'Ubuntu-16.04'}
      steps:
      - checkout: self
        submodules: false
      - task: UsePythonVersion@0
        displayName: setup python3.7
        inputs:
          versionSpec: '3.7'
      - script: 'python -m pip install -U --user --force-reinstall pep517 setuptools_scm'
        displayName: "Install build tools"
      - script: 'python -m pep517.build --source --out-dir wheelhouse .'
        displayName: "Build source distribution"
      - ${{ if parameters.test_extras }}:
        - script: ${{ format('python -m pip install $(find wheelhouse -name "*.tar.gz")[{0}]', parameters.test_extras) }}
          displayName: "Installing source distribution"
      - ${{ if not(parameters.test_extras) }}:
        - script: 'python -m pip install $(find wheelhouse -name "*.tar.gz")'
          displayName: "Installing source distribution"
      - ${{ if parameters.test_command }}:
        - script: ${{ parameters.test_command }}
          displayName: "Test source distribution"
      - publish: 'wheelhouse'
        artifact: ${{ target }}

- job: publish
  dependsOn: ${{ parameters.targets }}
  condition: succeeded()
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
  - checkout: none
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: Install Python 3.7
  - script: 'python -m pip install -U --user --force-reinstall twine'
    displayName: "install twine"
  # Get all artifacts from this build
  - ${{ each target in parameters.targets }}:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: 'wheelhouse'
        artifactName: ${{ target }}
  - script: 'ls -R wheelhouse'
  - task: TwineAuthenticate@0
    inputs:
      ${{ if parameters.external_feed }}:
        externalFeeds: ${{ parameters.external_feed}}
      ${{ if parameters.artifact_feed }}:
        artifactFeeds: ${{ parameters.artifact_feed}}
  - script:  ${{ format('python3.7 -m twine upload -r {0} --config-file $(PYPIRC_PATH) "wheelhouse/*"', parameters.pypi_remote) }}
    displayName: "upload sdist and wheels to PyPi"
